theme: minima

minima:
  skin: solarized-light
  social_links:
    platform: github
    user_url: "https://github.com/Zheng-Bote"

  page:
    title: My Github page

header_pages:
  - about.md
  - portfolio.md
