theme: minima

minima:
  skin: solarized-light
  social_links:
    platform: github
    user_url: https://github.com/Zheng-Bote

site:
  page:
    title: My Github page
  author:
    name: Zheng Robert
    email: no.spam@hotmail.com

header_pages:
  - about.md
  - portfolio.md
