theme: minima

minima:
  skin: solarized-light

author:
  name: Zheng Robert

page_created: 2024-08-24
page_created_year: 2024

imprint_url: https://www.robert.hase-zheng.net/website/about

header_pages:
  - about.md
  - portfolio.md
