name: Upload to GitHub
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create local Dir
        id: create_local_dir
        shell: bash
        run: |
          mkdir -p ./web/v0.3.0
          echo "# Changelog\n\n- fix: nix\n" > ./web/v0.3.0/Changelog.md
          echo "# SPDX\n\n- irgendwas\n" > ./web/v0.3.0/spdx.md

      - name: call action
        uses: ./.github/actions/upload_to_gh
        with:
          branch: main
          input-dir: ./web
          output-dir: ./Test
