name: test SBOM

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: zheng-bote/.github/workflows/wf_create_sbom.yml@main
    with:
      scanfile: /docs/package.json
    secrets: inherit
