name: Generate SemVer
# doof, na ja

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Previous tag
        run: |
          echo "prev tag: ${{ steps.previoustag.outputs.tag }}"

      - name: "Get next minor version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Next tag
        run: |
          echo "- MAJOR: ${{ steps.semvers.outputs.v_major }} | ${{ steps.semvers.outputs.major }}" >> $GITHUB_STEP_SUMMARY
          echo "- MINOR: ${{ steps.semvers.outputs.v_minor }} | ${{ steps.semvers.outputs.minor }}" >> $GITHUB_STEP_SUMMARY
          echo "- PATCH: ${{ steps.semvers.outputs.v_patch }} | ${{ steps.semvers.outputs.patch }}" >> $GITHUB_STEP_SUMMARY

      #- name: Trunk-Base
      #  id: semver-tag
      #  uses: gandarez/semver-action@master
      #  with:
      #    branching_model: "git-flow"

      - name: new trunk base
        id: semver-tag
        continue-on-error: true
        uses: wakatime/semver-action@v1.6.0
        with:
          prefix: ""
          prerelease_id: "alpha"
          main_branch_name: "main"
          develop_branch_name: "dev"
          debug: "true"

      
      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"

      - name: Next tag
        run: |
          echo "- Next: ${{ steps.semver-tag.outputs.semver_tag }}" >> $GITHUB_STEP_SUMMARY
