name: Generate SemVer
# doof, na ja

on:
  workflow_dispatch:
    inputs:
      Mayor:
        description: next SemVer is a Mayor
        type: boolean
        required: true
        default: false
      Minor:
        description: next SemVer is a Minor
        type: boolean
        required: true
        default: false
      Patch:
        description: next SemVer is a Patch
        type: boolean
        required: true
        default: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Previous tag
        run: |
          echo "prev tag: ${{ steps.previoustag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY

      - name: "Get next version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Next possible tag
        run: |
          echo "- MAJOR: ${{ steps.semvers.outputs.v_major }} | ${{ steps.semvers.outputs.major }}" >> $GITHUB_STEP_SUMMARY
          echo "- MINOR: ${{ steps.semvers.outputs.v_minor }} | ${{ steps.semvers.outputs.minor }}" >> $GITHUB_STEP_SUMMARY
          echo "- PATCH: ${{ steps.semvers.outputs.v_patch }} | ${{ steps.semvers.outputs.patch }}" >> $GITHUB_STEP_SUMMARY

      - name: choosen output
        run: echo "**Choosen Putput**" >> $GITHUB_STEP_SUMMARY
          
      - name: Next choosed tag Mayor
        if: ${{ inputs.Mayor }} == 'true'
        run: |
          echo "- MAJOR: ${{ steps.semvers.outputs.v_major }} | ${{ steps.semvers.outputs.major }}" >> $GITHUB_STEP_SUMMARY

      - name: Next choosed tag Minor
        if: ${{ inputs.Minor }} == 'true'
        run: |
          echo "- Minor: ${{ steps.semvers.outputs.v_minor }} | ${{ steps.semvers.outputs.minor }}" >> $GITHUB_STEP_SUMMARY

      - name: Next choosed tag Patch
        if: ${{ inputs.Patch }} == 'true'
        run: |
          echo "- MAJOR: ${{ steps.semvers.outputs.v_patch }} | ${{ steps.semvers.outputs.patch }}" >> $GITHUB_STEP_SUMMARY
