name: "test the action"
#author: "Zheng Bote"
#description: "test."

on:
  workflow_dispatch:
    inputs:
      name:
        description: "your name"
        required: true

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: check-out
        uses: actions/checkout@v4

      - name: Run my Action
        id: run-action
        uses: Zheng-Bote/gh-a_page_list-tags@main
        #uses: ./gh-a_page_list-tags@main
        with:
          name: ${{ inputs.name }}

      - name: Output
        run: |
          if [ "${{ env.MESSAGE }}" > 0 ]
          then
              echo "::info::funzt"
              exit 0
          fi
        env:
          MESSAGE: "${{ steps.run-action.outputs.message }}"
